"""
Interpretable-by-construction tiny language model (JAX).

Design under test:
  - Standard tiny transformer blocks (attn + MLP)
  - After every block, the residual stream is forced through a sparse
    non-negative top-k dictionary bottleneck: h -> code (sparse) -> D @ code
    => everything crossing a layer boundary is k named features.
  - Output logits = W_out @ (final bottleneck output) so logits decompose
    additively into per-feature contributions.
"""
import jax, jax.numpy as jnp, numpy as np, optax, time, json
from functools import partial

# ----------------------------------------------------------------------------
# Synthetic language with known latent causes
# ----------------------------------------------------------------------------
# Token layout: [MODE tokens: 0..M-1] [content tokens: M..M+C-1]
# Sequence: mode token, then a random content token, then T-2 tokens generated by the mode rule.
#   mode 0 "repeat":   x[t] = x[t-1]
#   mode 1 "succ":     x[t] = succ(x[t-1])  (cyclic within content vocab)
#   mode 2 "copy2":    x[t] = x[t-2]  (period-2 pattern; x[2] random)
#   mode 3 "pred":     x[t] = pred(x[t-1])
# Ground-truth latents per position: mode (0..3). Every prediction from t>=2 is
# deterministic given (mode, previous 1-2 tokens) -> a perfect model gets ~0 loss.

M_MODES = 4
C_TOK = 12
VOCAB = M_MODES + C_TOK

def gen_synthetic(n, T, rng):
    X = np.zeros((n, T), dtype=np.int32)
    modes = rng.integers(0, M_MODES, size=n)
    X[:, 0] = modes
    X[:, 1] = M_MODES + rng.integers(0, C_TOK, size=n)
    X[:, 2] = M_MODES + rng.integers(0, C_TOK, size=n)   # 2nd random tok (needed for copy2)
    for t in range(2, T):
        prev = X[:, t-1] - M_MODES
        prev2 = X[:, t-2] - M_MODES
        nxt = np.where(modes == 0, prev,
              np.where(modes == 1, (prev + 1) % C_TOK,
              np.where(modes == 2, prev2, (prev - 1) % C_TOK)))
        if t == 2:
            # keep random for t==2 except modes that only depend on prev
            nxt = np.where(modes == 2, X[:, 2] - M_MODES, nxt)
        X[:, t] = M_MODES + nxt
    return X, modes

# ----------------------------------------------------------------------------
# Model
# ----------------------------------------------------------------------------
def init_params(key, cfg):
    V, d, L, H, F, Dn = cfg['vocab'], cfg['d'], cfg['layers'], cfg['heads'], cfg['dict'], cfg['ff']
    ks = jax.random.split(key, 6 + 8 * L)
    s = 0.02
    p = {
        'emb': jax.random.normal(ks[0], (V, d)) * s,
        'pos': jax.random.normal(ks[1], (cfg['T'], d)) * s,
        'out': jax.random.normal(ks[2], (d, V)) * s,
        'ln_f': jnp.ones(d),
        'blocks': [],
    }
    if cfg.get('sparse_readout', 0) > 0:
        p['readout'] = jax.random.normal(ks[4], (F, V)) * s
    # dictionary: shared across layers if cfg['share_dict'] else per-layer
    def mkdict(k):
        D = jax.random.normal(k, (F, d))
        return D / jnp.linalg.norm(D, axis=1, keepdims=True)
    if cfg['bottleneck']:
        if cfg['share_dict']:
            p['dict'] = mkdict(ks[3])
            p['enc_b'] = jnp.zeros(F)
        p['emb_dict_bias'] = jnp.zeros(F)
    for l in range(L):
        kk = ks[6 + 8 * l: 6 + 8 * (l + 1)]
        b = {
            'ln1': jnp.ones(d), 'ln2': jnp.ones(d),
            'wq': jax.random.normal(kk[0], (d, d)) * s, 'wk': jax.random.normal(kk[1], (d, d)) * s,
            'wv': jax.random.normal(kk[2], (d, d)) * s, 'wo': jax.random.normal(kk[3], (d, d)) * s,
            'w1': jax.random.normal(kk[4], (d, Dn)) * s, 'b1': jnp.zeros(Dn),
            'w2': jax.random.normal(kk[5], (Dn, d)) * s, 'b2': jnp.zeros(d),
        }
        if cfg['bottleneck'] and not cfg['share_dict']:
            b['dict'] = mkdict(kk[6]); b['enc_b'] = jnp.zeros(F)
        if cfg.get('code_residual', False):
            b['enc_b'] = jnp.zeros(F)
        p['blocks'].append(b)
    return p

def ln(x, g, eps=1e-5):
    m = x.mean(-1, keepdims=True); v = ((x - m) ** 2).mean(-1, keepdims=True)
    return (x - m) / jnp.sqrt(v + eps) * g

def topk_mask(z, k):
    # z: (..., F). keep k largest (values >0), zero the rest. Straight-through not needed:
    # gradient flows through kept entries only (like JumpReLU/TopK SAE).
    thr = jnp.sort(z, axis=-1)[..., -k][..., None]
    return jnp.where(z >= thr, z, 0.0)

def bottleneck(h, D, enc_b, k, feat_mask=None):
    """Encode dense h into sparse non-negative code over dictionary D (F,d) and decode.
    Tied encoder/decoder (encoder = D^T) so each feature has ONE direction => one meaning.
    Returns decoded h', code."""
    z = jax.nn.relu(h @ D.T + enc_b)         # (..., F)
    code = topk_mask(z, k)
    if feat_mask is not None:
        code = code * feat_mask
    out = code @ D
    return out, code, (z, h - out, D)

def attn(x, b, H, mask):
    Tn, d = x.shape[-2], x.shape[-1]; hd = d // H
    q = (x @ b['wq']).reshape(*x.shape[:-1], H, hd)
    k_ = (x @ b['wk']).reshape(*x.shape[:-1], H, hd)
    v = (x @ b['wv']).reshape(*x.shape[:-1], H, hd)
    a = jnp.einsum('...thd,...shd->...hts', q, k_) / jnp.sqrt(hd)
    a = jnp.where(mask, a, -1e9)
    a = jax.nn.softmax(a, -1)
    o = jnp.einsum('...hts,...shd->...thd', a, v).reshape(*x.shape[:-1], d)
    return o @ b['wo'], a

def forward(p, cfg, x, feat_masks=None, return_all=False, return_aux=False):
    """x: (B,T) ints. feat_masks: optional list (per bottleneck, len L+1) of (F,) or (B,T,F) masks for ablation."""
    B, T = x.shape
    d, L, H, k = cfg['d'], cfg['layers'], cfg['heads'], cfg['k']
    h = p['emb'][x] + p['pos'][:T][None]
    mask = jnp.tril(jnp.ones((T, T), bool))[None, None]
    codes, attns, auxs = [], [], []
    def bn(h, l):
        if not cfg['bottleneck']:
            return h, None, None
        D = p['dict'] if cfg['share_dict'] else p['blocks'][l]['dict']
        eb = p['enc_b'] if cfg['share_dict'] else p['blocks'][l]['enc_b']
        fm = None if feat_masks is None else feat_masks[l + 1]
        return bottleneck(h, D, eb, k, fm)
    # embedding bottleneck (index 0) — so even the input is expressed as features
    if cfg['bottleneck'] and cfg['bottleneck_emb']:
        D0 = p['dict'] if cfg['share_dict'] else p['blocks'][0]['dict']
        fm = None if feat_masks is None else feat_masks[0]
        h, c, ax = bottleneck(h, D0, p['emb_dict_bias'], k, fm); codes.append(c); auxs.append(ax)
    else:
        codes.append(None); auxs.append(None)
    code = codes[0]
    deltas = []
    for l, b in enumerate(p['blocks']):
        if cfg.get('code_residual', False):
            # ---- v3: code-space residual -------------------------------------------------
            D = p['dict']
            a, A = attn(ln(h, b['ln1']), b, H, mask); attns.append(A)
            m = jax.nn.gelu(ln(h + a, b['ln2']) @ b['w1'] + b['b1']) @ b['w2'] + b['b2']
            upd = a + m                                   # dense update the block wants to write
            dz = upd @ D.T + b['enc_b']                   # project update onto dictionary (signed)
            # sparse signed write: keep k_write largest-magnitude entries
            kw = cfg['k_write']
            thr = jnp.sort(jnp.abs(dz), axis=-1)[..., -kw][..., None]
            delta = jnp.where(jnp.abs(dz) >= thr, dz, 0.0)
            deltas.append(delta)
            z = code + delta                              # persistence by default
            newcode = topk_mask(jax.nn.relu(z), k)
            fm = None if feat_masks is None else feat_masks[l + 1]
            if fm is not None: newcode = newcode * fm
            code = newcode
            h = code @ D
            codes.append(code); auxs.append((jax.nn.relu(z), upd - delta @ D, D))  # FIX (2026-09-12 review): AuxK target is the part of the update the sparse write missed, not the whole update
        else:
            a, A = attn(ln(h, b['ln1']), b, H, mask); attns.append(A)
            h = h + a
            m = jax.nn.gelu(ln(h, b['ln2']) @ b['w1'] + b['b1']) @ b['w2'] + b['b2']
            h = h + m
            h, c, ax = bn(h, l); codes.append(c); auxs.append(ax)
    if cfg['bottleneck'] and cfg.get('sparse_readout', 0) > 0:
        # v4: each feature may vote for at most m output tokens (row-wise top-m of readout R)
        R = p['readout']; m = cfg['sparse_readout']
        thr = jnp.sort(jnp.abs(R), axis=-1)[:, -m][:, None]
        Rs = jnp.where(jnp.abs(R) >= thr, R, 0.0)
        Rs = Rs + (R - jax.lax.stop_gradient(R)) * cfg.get('readout_ste', 1.0)   # straight-through grad to all entries
        logits = codes[-1] @ Rs
    elif cfg['bottleneck']:
        logits = h @ p['out']          # linear in final sparse code: logits = code @ (D @ out)
    else:
        logits = ln(h, p['ln_f']) @ p['out']
    if return_aux:
        return logits, codes, attns, auxs
    if return_all:
        return logits, codes, attns
    return logits

def loss_fn(p, cfg, x, aux_coef=0.0):
    logits, codes, _, auxs = forward(p, cfg, x, return_aux=True)
    lg = logits[:, :-1]; tgt = x[:, 1:]
    lp = jax.nn.log_softmax(lg, -1)
    nll = -jnp.take_along_axis(lp, tgt[..., None], -1).mean()
    aux = 0.0
    if cfg['bottleneck'] and aux_coef > 0:
        # AuxK (differentiable): features unused in this batch get gradient by being asked
        # to reconstruct the bottleneck's residual error. Prevents dead features.
        for c, ax in zip(codes, auxs):
            if c is None: continue
            z, err, D = ax
            used = (c > 0).any(axis=(0, 1))                       # (F,) fired anywhere in batch
            z_dead = jnp.where(used[None, None, :], 0.0, z)
            code_dead = topk_mask(z_dead, cfg['k_aux'])
            recon = code_dead @ D
            aux = aux + jnp.mean((jax.lax.stop_gradient(err) - recon) ** 2)
    if cfg['bottleneck'] and cfg.get('ortho', 0) > 0 and cfg['share_dict']:
        D = p['dict']; G = D @ D.T
        aux = aux + cfg['ortho'] * jnp.mean((G - jnp.eye(G.shape[0])) ** 2) * G.shape[0]
    return nll + aux_coef * aux, nll

def make_train(cfg, lr, aux_coef, steps=1000):
    sched = optax.warmup_cosine_decay_schedule(0.0, lr, min(100, steps // 10), steps, lr*0.05)
    opt = optax.chain(optax.clip_by_global_norm(1.0), optax.adamw(sched, weight_decay=0.01))
    @jax.jit
    def step(p, os, x):
        (l, nll), g = jax.value_and_grad(loss_fn, has_aux=True)(p, cfg, x, aux_coef)
        upd, os = opt.update(g, os, p)
        p = optax.apply_updates(p, upd)
        # renormalize dictionary rows so features are unit directions
        if cfg['bottleneck']:
            if cfg['share_dict']:
                p['dict'] = p['dict'] / jnp.linalg.norm(p['dict'], axis=1, keepdims=True)
            else:
                for b in p['blocks']:
                    b['dict'] = b['dict'] / jnp.linalg.norm(b['dict'], axis=1, keepdims=True)
        return p, os, nll
    return opt, step

def train(cfg, data, steps, lr=3e-3, bs=64, aux_coef=0.0, seed=0, log_every=200, eval_data=None):
    key = jax.random.PRNGKey(seed)
    p = init_params(key, cfg)
    opt, step = make_train(cfg, lr, aux_coef, steps)
    os = opt.init(p)
    rng = np.random.default_rng(seed)
    hist = []
    t0 = time.time()
    for i in range(steps):
        idx = rng.integers(0, len(data), bs)
        p, os, nll = step(p, os, jnp.asarray(data[idx]))
        if i % log_every == 0 or i == steps - 1:
            ev = float(eval_loss(p, cfg, eval_data)) if eval_data is not None else float('nan')
            hist.append((i, float(nll), ev))
            print(f"  step {i:5d} train_nll {float(nll):.4f} eval_nll {ev:.4f}  ({time.time()-t0:.0f}s)", flush=True)
    return p, hist

@partial(jax.jit, static_argnums=(1,))
def _eval(p, cfg_t, x):
    cfg = dict(cfg_t)
    return loss_fn(p, cfg, x, 0.0)[1]

def eval_loss(p, cfg, data, bs=256):
    cfg_t = tuple(sorted(cfg.items()))
    tot, n = 0.0, 0
    for i in range(0, len(data), bs):
        xb = jnp.asarray(data[i:i + bs]); tot += float(_eval(p, cfg_t, xb)) * len(xb); n += len(xb)
    return tot / n

def base_cfg(**kw):
    cfg = dict(vocab=VOCAB, d=64, layers=2, heads=2, ff=128, T=16, dict=128, k=8,
               bottleneck=True, share_dict=True, bottleneck_emb=True, k_aux=8, code_residual=False, k_write=8)
    cfg.update(kw)
    return cfg
